name: Build and Release

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build webpack bundle
        run: npm run build

      - name: Check for existing portable executable
        shell: powershell
        run: |
          Write-Host "🔍 Checking for existing executable..."
          if (Test-Path "Markdown Viewer 1.0.0.exe") {
            Write-Host "✅ Found existing Markdown Viewer 1.0.0.exe"
            $size = (Get-Item "Markdown Viewer 1.0.0.exe").Length / 1MB
            Write-Host "📏 Size: $([math]::Round($size, 2)) MB"
          } else {
            Write-Host "❌ Markdown Viewer 1.0.0.exe not found, building..."
            npm run build-portable
          }

      - name: Prepare executable for release
        shell: powershell
        run: |
          Write-Host "📦 Preparing executable for release..."
          mkdir -Force release-artifacts
          
          if (Test-Path "Markdown Viewer 1.0.0.exe") {
            Copy-Item "Markdown Viewer 1.0.0.exe" "release-artifacts/"
            Write-Host "✅ Copied Markdown Viewer 1.0.0.exe to release artifacts"
            
            # Verify the copy
            if (Test-Path "release-artifacts/Markdown Viewer 1.0.0.exe") {
              $size = (Get-Item "release-artifacts/Markdown Viewer 1.0.0.exe").Length / 1MB
              Write-Host "✅ Verified: Release artifact size $([math]::Round($size, 2)) MB"
            } else {
              Write-Host "❌ Failed to copy to release artifacts folder"
              exit 1
            }
          } else {
            Write-Host "❌ Markdown Viewer 1.0.0.exe not found in root"
            Get-ChildItem -Name "*.exe"
            exit 1
          }

      - name: Upload Windows executable
        uses: actions/upload-artifact@v3
        with:
          name: markdown-viewer-executable
          path: release-artifacts/Markdown Viewer 1.0.0.exe
          retention-days: 30

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build-windows
    runs-on: ubuntu-latest

    steps:
      - name: Download executable artifact
        uses: actions/download-artifact@v3
        with:
          name: markdown-viewer-executable

      - name: Verify downloaded executable
        run: |
          echo "🔍 Verifying downloaded executable:"
          ls -la
          if [ -f "Markdown Viewer 1.0.0.exe" ]; then
            echo "✅ Found Markdown Viewer 1.0.0.exe"
            echo "📏 Size: $(du -h 'Markdown Viewer 1.0.0.exe' | cut -f1)"
          else
            echo "❌ Executable not found!"
            exit 1
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: Markdown Viewer 1.0.0.exe
          draft: false
          prerelease: false
          name: Markdown Viewer ${{ github.ref_name }}
          body: |
            ## 🚀 Markdown Viewer ${{ github.ref_name }}
            
            ### 📥 Download:
            **Windows Portable**: `Markdown Viewer 1.0.0.exe`
            
            ### ✨ Features:
            - ✅ Markdown editor with live preview
            - ✅ File explorer and tabs
            - ✅ Custom application icon
            - ✅ Completely portable - no installation required
            
            ### 🚀 How to use:
            1. Download `Markdown Viewer 1.0.0.exe`
            2. Run it directly - no installation needed!
            3. Start editing your markdown files
            
            **Note**: This is a portable Windows executable that works without installation.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 