name: Build and Release

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build webpack bundle
        run: npm run build

      - name: Check for existing portable executable (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Write-Host "🔍 Checking for existing executable..."
          if (Test-Path "Markdown Viewer 1.0.0.exe") {
            Write-Host "✅ Found existing Markdown Viewer 1.0.0.exe"
            $size = (Get-Item "Markdown Viewer 1.0.0.exe").Length / 1MB
            Write-Host "📏 Size: $([math]::Round($size, 2)) MB"
          } else {
            Write-Host "❌ Markdown Viewer 1.0.0.exe not found, building..."
            npm run build-portable
          }

      - name: Build Electron app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run dist:mac

      - name: Build Electron app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist:linux

      - name: Prepare Windows artifacts
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Write-Host "📦 Preparing Windows artifacts..."
          mkdir -Force artifacts
          
          if (Test-Path "Markdown Viewer 1.0.0.exe") {
            Copy-Item "Markdown Viewer 1.0.0.exe" "artifacts/"
            Write-Host "✅ Copied Markdown Viewer 1.0.0.exe to artifacts"
            
            # Verify the copy
            if (Test-Path "artifacts/Markdown Viewer 1.0.0.exe") {
              $size = (Get-Item "artifacts/Markdown Viewer 1.0.0.exe").Length / 1MB
              Write-Host "✅ Verified: Artifact size $([math]::Round($size, 2)) MB"
            } else {
              Write-Host "❌ Failed to copy to artifacts folder"
              exit 1
            }
          } else {
            Write-Host "❌ Markdown Viewer 1.0.0.exe not found in root"
            Get-ChildItem -Name "*.exe"
            exit 1
          }

      - name: Upload Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-portable-exe
          path: artifacts/Markdown Viewer 1.0.0.exe
          retention-days: 30

      - name: Upload artifacts (Mac/Linux)
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: List downloaded artifacts
        run: |
          echo "📁 Available artifacts:"
          find . -name "*" -type f | head -20
          echo ""
          echo "🔍 Looking for executable:"
          find . -name "*.exe" -type f
          ls -la

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-portable-exe/Markdown Viewer 1.0.0.exe
            ubuntu-latest-build/*
            macos-latest-build/*
          draft: false
          prerelease: false
          name: Markdown Viewer ${{ github.ref_name }}
          body: |
            ## 🚀 Markdown Viewer Release ${{ github.ref_name }}
            
            ### 📥 Downloads:
            - **Windows (Portable)**: `Markdown Viewer 1.0.0.exe` - No installation required!
            - **macOS**: `.dmg` installer
            - **Linux**: `.AppImage` and `.deb` packages
            
            ### ✨ Features:
            - ✅ Markdown editor with live preview
            - ✅ File explorer and tabs
            - ✅ Custom application icon
            - ✅ Portable executable for Windows (no installation needed)
            - ✅ Cross-platform support
            
            ### 🚀 How to use:
            **Windows**: Just download and run `Markdown Viewer 1.0.0.exe` - it's completely portable!
            
            **macOS/Linux**: Download and install the appropriate package for your system.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 