name: Build and Release

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build webpack bundle
        run: npm run build

      - name: Build Portable Executable (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build-portable

      - name: Build Electron app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run dist:mac

      - name: Build Electron app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run dist:linux

      - name: Prepare Windows artifacts
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          mkdir -p artifacts
          if (Test-Path "Markdown Viewer 1.0.0.exe") {
            Copy-Item "Markdown Viewer 1.0.0.exe" "artifacts/"
            Write-Host "✅ Copied Markdown Viewer 1.0.0.exe to artifacts"
          } else {
            Write-Host "❌ Markdown Viewer 1.0.0.exe not found"
            exit 1
          }

      - name: Upload Windows artifacts
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: windows-portable
          path: artifacts/

      - name: Upload artifacts (Mac/Linux)
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: List downloaded artifacts
        run: |
          echo "📁 Available artifacts:"
          find . -name "*.exe" -o -name "*.dmg" -o -name "*.AppImage" -o -name "*.deb" | head -20

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-portable/*
            ubuntu-latest-build/*
            macos-latest-build/*
          draft: false
          prerelease: false
          body: |
            ## 🚀 Markdown Viewer Release
            
            ### Downloads:
            - **Windows**: `Markdown Viewer 1.0.0.exe` (Portable - no installation required)
            - **macOS**: `.dmg` installer
            - **Linux**: `.AppImage` and `.deb` packages
            
            ### Features:
            - ✅ Markdown editor with live preview
            - ✅ Custom application icon
            - ✅ Portable executable for Windows
            - ✅ Cross-platform support
            
            Simply download and run the executable for your platform!
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 